// Code generated by goctl. DO NOT EDIT.
// Source: imrpc.proto

package imrpcclient

import (
	"context"

	"github.com/zhoushuguang/zeroim/imrpc/imrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest       = imrpc.LoginRequest
	LoginResponse      = imrpc.LoginResponse
	LogoutRequest      = imrpc.LogoutRequest
	LogoutResponse     = imrpc.LogoutResponse
	PostMessageReponse = imrpc.PostMessageReponse
	PostMessageRequest = imrpc.PostMessageRequest

	Imrpc interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
		PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageReponse, error)
	}

	defaultImrpc struct {
		cli zrpc.Client
	}
)

func NewImrpc(cli zrpc.Client) Imrpc {
	return &defaultImrpc{
		cli: cli,
	}
}

func (m *defaultImrpc) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := imrpc.NewImrpcClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultImrpc) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := imrpc.NewImrpcClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultImrpc) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageReponse, error) {
	client := imrpc.NewImrpcClient(m.cli.Conn())
	return client.PostMessage(ctx, in, opts...)
}
